# Configuración para Netlify

[build]
  command = "npm run build"
  publish = "dist"

# Configuración de redirecciones
[[redirects]]
  from = "/api/*"
  to = "/:splat"
  status = 200

# Redirección para SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configuración de cabeceras para permitir CORS
[[headers]]
  for = "/api/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"

# Configuración de cabeceras para el favicon
[[headers]]
  for = "/favicon.ico"
    [headers.values]
    Cache-Control = "public, max-age=31536000"

# Configuración para CloudFlare
[build.environment]
  CLOUDFLARE_API_TOKEN = "null_token"

# Trabajador para manejar funciones
[functions]
  directory = "netlify/functions"
